steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - >-
        $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - -c 
      - ./deploy_rev.sh
    env:
       - _SERVICE_NAME=$_SERVICE_NAME
       - _AR_HOSTNAME=$_AR_HOSTNAME
       - PROJECT_ID=$PROJECT_ID
       - REPO_NAME=$REPO_NAME
       - COMMIT_SHA=$COMMIT_SHA
       - BUILD_ID=$BUILD_ID
       - _TRIGGER_ID=$_TRIGGER_ID
       - _DEPLOY_REGION=$_DEPLOY_REGION
       - PROJECT_NUMBER=$PROJECT_NUMBER
    entrypoint: bash
images:
  - >-
    $_AR_HOSTNAME/$PROJECT_ID/cloud-run-source-deploy/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
substitutions:
  _SERVICE_NAME: flex-chat
  _DEPLOY_REGION: us-central1
  _AR_HOSTNAME: us-central1-docker.pkg.dev
  _PLATFORM: managed
  _TRIGGER_ID: 348c8eee-9c66-45e8-91ab-8a24c6e99787
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - flex-chat
